### ISSUE TITLE
Batch distribution return None

### ISSUE THREAD

**Issue by ZhuJiaqi9905** [insujang/oobleck#16]
When nodes reconfigure occurs, the algorithm will calculate throughput with batch distribution, the relevant code is `_distribute_batch` function in instantiator.py. However, I find that the function will return None due to the following case:
``` 
  if not all(model.nb[i].value for i in model.I):
      return None
```

That will cause an error in creating a `HeterogeneousPipelinesExecutionPlan` object, since the member `num_microbatches_set` is None. I wonder how to fix it? Many thanks.

**Comment by insujang** [comment]
Currently the entire Oobleck is being refactored, including changing ILP solver with others (#18). I'll let you know when it is done. Please try it again later.

**Comment by ZhuJiaqi9905** [comment]
Thanks. It seems that the Oobleck is rewrited in rust. That's cool!

**Comment by insujang** [comment]
Hi, #18 has just been merged. Could you please try again? Although it is newly written and functionally works, but still may generate wrong results. Please reopen this issue or create a new one if you see weird behavior. Thanks!
