### ISSUE TITLE
How Oobleck supports both fsdp and resilient?

### ISSUE THREAD

**Issue by ZhuJiaqi9905** [insujang/oobleck#24]
Hello, I want to ask how Oobleck supports both fsdp and resilient?

Take a simple example. Assuming there are two nodes, each node has 4 GPU. The model has 4 layers and can be splited into 4 pipeline stage, and each GPU maps a pipeline stage. 

Now the data parallel group is 2:
```
Node0: 
La | Lb | Lc |Ld |
---|----|---|--- |
a0 | b0 | c0| d0  |
a1 | b1 | c1 | d1 |


Node1: 
La | Lb | Lc |Ld   |
---|---- |---|--- |
a0 | b0 | c0| d0  |
a1 | b1 | c1 | d1 |
```

The above "La, Lb, Lc, Ld" refer to "layer a, layer b, layer c, layer d". The "a0, a1" means "Layer a can be shard to a0 and a1".  

When node0 fails, node1 can run contiuously since node0 and node1 both holds the entire model, which is resilient.

However, if we support fsdp, the model state will be sharded by data parallel groups. Which means: 
```
Node0: 
La | Lb | Lc |Ld   |
---|---- |---|--- |
a0 | b0 | c0| d0  |


Node1: 
La | Lb | Lc |Ld   |
---|---- |---|--- |
a1 | b1 | c1 | d1 |
```

When node0 fails, node1 can not continue to run, because node1 doesn't hold the entire model.

So, how Oobleck supports both fsdp and resilient? Maybe I misunderstand something.  
Could you please explain it in detail? Many thanks!

**Comment by insujang** [comment]
After changing its backend to ColossalAI, it does no longer support fsdp, but only 3D parallelism. I made this decision after realizing that combining pipeline parallelism and fsdp is not efficient, cause for every microbatch it needs to have communication to transfer gradients. See [this discussion](https://github.com/hpcaitech/ColossalAI/issues/682) for details. In theory, however, FSDP can still be used as a replacement of tensor parallelism within nodes in Oobleck policy.

Even with FSDP used, you still need to use traditional data parallelism (no FSDP) across nodes to provide replica for resiliency. Your example does not have any replica, and it is not how Oobleck is supposed to work. This is the correct example if FSDP is used:
```
Node0:
GPU0 | GPU1 | GPU2 | GPU3
---- | ---- | ---- | ----
L0a  | L0b  | L2a  | L2b
L1a  | L1b  | L3a  | L3b

Node1:
GPU4 | GPU5 | GPU6 | GPU7
---- | ---- | ---- | ----
L0a  | L0b  | L2a  | L2b
L1a  | L1b  | L3a  | L3b
```
Explanation: A model has 4 layers (L0, L1, L2, L3). Each is sharded across 2 GPUs (Lxa, Lxb), thus FSDP parallel degree is 2. Pipeline has 2 stages, each of which has [L0, L1] and [L2, L3] layers. Thus, in node 0, GPU0 and GPU1 have sharded stage 0, and GPU 2 and GPU 3 have sharded stage 1.
4 GPUs can hold one copy of the model with 2 pipeline stages and 2 FSDP parallel degree.

To introduce replica, node 1 has the same configuration. After node 0 fails, node 1 still has the entire model states, which can continue to run.

**Comment by ZhuJiaqi9905** [comment]
Thanks, I got it!
