### ISSUE TITLE
cornstarch releasing?

### ISSUE THREAD

**Issue by laochonlam** [insujang/oobleck#25]
Hi @insujang,

Great work, thanks for releasing Oobleck! Are you planning to release [cornstarch](https://github.com/Symbioticlab/cornstarch) as well per the README mentioned? Thank you!

Lam

**Comment by insujang** [comment]
Hi @laochonlam!

Yes, we plan to release Cornstarch as well. Planning to release it by the end of this year.

**Comment by laochonlam** [comment]
Great, looking forward to it. Thank you!

Lam
